[package]
name = "f"
version = "0.1.0"
authors = ["Brian King <brian.king@adhoc.team>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
regex = "1"
structopt = "0.3"
